### ISSUE TITLE
Photo aspect ratio changes and rotates

### ISSUE THREAD

**Issue by kazuyasi** [quentintaranpino/nostrcheck-server#29]
**Describe the bug**
The uploaded photo was rotated and the aspect ratio became abnormal.

**Original photo**
3.1MB
3024x4032
https://drive.google.com/file/d/1stQAFOBVGNknpoHQzf4hoZDvBRD1TW-X/view?usp=share_link

**Uploaded photo**
https://nostrcheck.me/media/f695699a89489948011d24875db97a5b0929d46ce1315756242795a0969b35f3/36e3cbbd61c4fa47fc4969677bea6310b96a8fbb966fec62c780ba4b39660179.webp

**Smartphone**
 - Device: iPhone15
 - OS: iOS 18.0.1
 - Browser safari
 - Version 18.0.1

**Comment by quentintaranpino** [comment]
Fixed in build 0.6.2010. Thank you very much for reporting the issue!

**Comment by kazuyasi** [comment]
I have confirmed that the issue is resolved.
Thank you for your early action!
