### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by xjmzx** [quentintaranpino/nostrcheck-server#30]
**Describe the bug**
After running install script `curl https://raw.githubusercontent.com/quentintaranpino/nostrcheck-api-ts/main/scripts/install.sh --output install.sh && chmod +x install.sh && ./install.sh` server fails to start with `cd nostrcheck-api-ts && npm run start`

**To Reproduce**
`curl https://raw.githubusercontent.com/quentintaranpino/nostrcheck-api-ts/main/scripts/install.sh --output install.sh && chmod +x install.sh && ./install.sh` go through the options as necessary, in my case, chose a database name, supplied my own hostname, opted for certs through certbot, supplied my own pub/priv key, default media location selection. All completed without error. Until I tried to start the server.

**Expected behavior**
I expected the server to start. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS x86_64

**Additional context**
The error I get when trying to run `npm run start` from the `nostrcheck-api-ts` directory:

```
> nostrcheck-api-ts@0.5.0.1478 start
> node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm ./dist/init.js


node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Cannot find module 'typescript'
Require stack:
- /home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/util.js
- /home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/index.js
- /home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/esm.js
- /home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/esm.mjs
    at Function._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at projectLocalResolveHelper (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/util.ts:130:20)
    at resolveCompiler (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/configuration.ts:348:20)
    at resolveAndLoadCompiler (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/configuration.ts:340:24)
    at findAndReadConfig (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/configuration.ts:72:26)
    at create (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/index.ts:623:46)
    at register (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/index.ts:591:15)
    at Object.registerAndCreateEsmHooks (/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/src/esm.ts:116:34)
    at file:///home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/esm.mjs:8:7 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/util.js',
    '/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/index.js',
    '/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/dist/esm.js',
    '/home/xplbzx/nostrcheck-api-ts/node_modules/ts-node/esm.mjs'
  ]
}
```

**Comment by quentintaranpino** [comment]
Hi @xjmzx 

The issue you're facing typically happens when the typescript module isn’t installed as a dependency. First, try running `npm install typescript --save-dev` in the `nostrcheck-api-ts` directory to ensure TypeScript is installed. Afterward, reinstall all dependencies by running `npm install` to confirm everything is in place.

If the issue persists, clearing the npm cache may help. You can do this with `npm cache clean --force`

Let me know if these steps help or if there's still an error.

**Comment by xjmzx** [comment]
Hi thanks for replying. 

I started afresh, reinstalled nodejs and ran the install script and this time didn't get any error about npm packages. 
Is it that I was misconfigured with the wrong nodejs version? I ran: 
```
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
apt install nodejs
```
but I noticed `node --version` shows `v21.7.3`

unrelated, but the error I got this time was:

```
Starting Nostrcheck server
Missing config key: environment - Adding default value: development
Missing config key: name - Adding default value: nostraddress
Missing config key: enabled - Adding default value: true
Missing config key: path - Adding default value: /nostraddress
Missing config key: methods - Adding default value: [ 'GET' ]
```

Navigating to https://mydomain.com shows nginx, and 'further configuration needed.'

**Comment by xjmzx** [comment]
Just want to add that installation is working without the npm dependancy issue, so I'll close this.
